version: '3.8'

services:
  postgres_job:
    image: postgres:15
    container_name: postgres_job
    restart: always
    environment:
      POSTGRES_USER: job_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: job_db
    ports:
      - "5434:5432"  # Map host port 5434 to container port 5432
    networks:
      - divar_network

  postgres_crawler:
    image: postgres:15
    container_name: postgres_crawler
    restart: always
    environment:
      POSTGRES_USER: crawler_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crawler_db
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    networks:
      - divar_network

  job:
    build:
      context: ./job
      dockerfile: Dockerfile
    container_name: job_service
    ports:
      - "8001:8001"
    networks:
      - divar_network
    depends_on:
      - postgres_job

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler_service
    ports:
      - "8000:8000"
    networks:
      - divar_network
    depends_on:
      - postgres_crawler

networks:
  divar_network:
    driver: bridge
