version: '3.8'

services:
  job:
    build:
      context: ./job
      dockerfile: Dockerfile
    container_name: job_service
    ports:
      - "8000:8000"
    networks:
      - divar_network

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler_service
    ports:
      - "8001:8001"
    networks:
      - divar_network
    depends_on:
      - job

networks:
  divar_network:
    driver: bridge
